 version: '2'
 services:
   backend:
     build: ./backend
     ports:
      - "80:5000"
   frontend:
    build: ./frontend
    privileged: true
    labels:
      io.resin.features.kernel-modules: "true"
      io.resin.features.firmware: "true"
